Feature/cu c8hp87
developDomo/SRIE pull request #132
Opened 2020-09-28 23:45 UTC by sasasamaes

Aqui se resolvieron estos tickets: 
https://app.clickup.com/t/cppw07
https://app.clickup.com/t/c8hp87
https://app.clickup.com/t/cppvtm

2020-09-28 23:46 UTC, credondocr commented
Task linked: [CU-c8hp87 DATOS PAIS / BLOQUE CATEGORÍAS: Agregar a cada botón el enlace a la página de resultados de indicadores con el filtro de la categoría correspondiente](https://app.clickup.com/t/c8hp87)

2020-10-07 17:30 UTC, credondocr requested changes

2020-10-07 17:30 UTC, credondocr commented on pages/[id]/index.js
> +      </Container> */}
que es */ ?

2020-10-08 22:02 UTC, sasasamaes commented on pages/[id]/index.js
> +      </Container> */}
Hola! en uno de los tickets se pidio ocultar por mientras el banner :)

2020-10-09 01:55 UTC, credondocr approved these changes

2020-10-09 01:56 UTC, merged